[package]
name = "tlauc"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
csv = "1.1.6"
serde = { version = "1.0.149", features = ["derive"] }
tree-sitter = "0.20.9"
tree-sitter-tlaplus = "0.6.2"
