[package]
name = "tlaplus-unicode-converter"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
csv = "1.1.6"
serde = { version = "1.0.130", features = ["derive"] }
tree-sitter = "0.19.5"
tree-sitter-tlaplus = "0.2.0"
