name: Release
on:
  release:
    types: [created]
jobs:
  rust-crate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Check Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
      - name: Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{secrets.CRATES_AUTH_TOKEN}}
